import type { Contact, Transaction, Account, Card, MoneyRequest } from "./types"

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "María González",
    phone: "+54 9 11 1234-5678",
    email: "maria.gonzalez@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [
      { amount: 15000, date: "15/01", type: "sent" },
      { amount: 8500, date: "10/01", type: "received" },
    ],
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    phone: "+54 9 11 2345-6789",
    email: "carlos.rodriguez@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 25000, date: "12/01", type: "sent" }],
  },
  {
    id: "3",
    name: "Ana Martínez",
    phone: "+54 9 11 3456-7890",
    email: "ana.martinez@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: false,
    recentTransfers: [],
  },
  {
    id: "4",
    name: "Luis Fernández",
    phone: "+54 9 11 4567-8901",
    email: "luis.fernandez@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 12000, date: "08/01", type: "received" }],
  },
  {
    id: "5",
    name: "Sofia López",
    phone: "+54 9 11 5678-9012",
    email: "sofia.lopez@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: false,
    recentTransfers: [],
  },
  {
    id: "6",
    name: "Diego Morales",
    phone: "+54 9 11 6789-0123",
    email: "diego.morales@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 18000, date: "05/01", type: "sent" }],
  },
  {
    id: "7",
    name: "Valentina Silva",
    phone: "+54 9 11 7890-1234",
    email: "valentina.silva@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: false,
    recentTransfers: [],
  },
  {
    id: "8",
    name: "Mateo Herrera",
    phone: "+54 9 11 8901-2345",
    email: "mateo.herrera@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 22000, date: "03/01", type: "received" }],
  },
  {
    id: "9",
    name: "Isabella Castro",
    phone: "+54 9 11 9012-3456",
    email: "isabella.castro@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: false,
    recentTransfers: [],
  },
  {
    id: "10",
    name: "Sebastián Ruiz",
    phone: "+54 9 11 0123-4567",
    email: "sebastian.ruiz@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 9500, date: "01/01", type: "sent" }],
  },
  {
    id: "11",
    name: "Camila Torres",
    phone: "+54 9 11 1234-5679",
    email: "camila.torres@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: false,
    recentTransfers: [],
  },
  {
    id: "12",
    name: "Joaquín Vargas",
    phone: "+54 9 11 2345-6780",
    email: "joaquin.vargas@email.com",
    avatar: "/placeholder-user.jpg",
    isFrequent: true,
    recentTransfers: [{ amount: 16000, date: "28/12", type: "received" }],
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    type: "transfer",
    amount: -15000,
    description: "Transferencia a María González",
    date: "2024-01-15",
    status: "completed",
    category: "Transferencias",
    contactName: "María González",
    balance: 125430.5,
  },
  {
    id: "txn_002",
    type: "deposit",
    amount: 50000,
    description: "Depósito en efectivo",
    date: "2024-01-14",
    status: "completed",
    category: "Depósitos",
    balance: 140430.5,
  },
  {
    id: "txn_003",
    type: "payment",
    amount: -8500,
    description: "Pago de servicios - Luz",
    date: "2024-01-13",
    status: "completed",
    category: "Servicios",
    balance: 90430.5,
  },
  {
    id: "txn_004",
    type: "transfer",
    amount: -25000,
    description: "Transferencia a Carlos Rodríguez",
    date: "2024-01-12",
    status: "completed",
    category: "Transferencias",
    contactName: "Carlos Rodríguez",
    balance: 98930.5,
  },
  {
    id: "txn_005",
    type: "income",
    amount: 120000,
    description: "Salario - Enero 2024",
    date: "2024-01-10",
    status: "completed",
    category: "Ingresos",
    balance: 123930.5,
  },
]

export const mockAccount: Account = {
  id: "acc_001",
  userId: "user_001",
  accountNumber: "1234567890",
  balance: 125430.5,
  currency: "ARS",
  accountType: "checking",
  isActive: true,
  createdAt: "2023-01-01T00:00:00Z",
  updatedAt: "2024-01-15T10:30:00Z",
}

export const mockCards: Card[] = [
  {
    id: "card_001",
    accountId: "acc_001",
    cardNumber: "**** **** **** 1234",
    cardType: "debit",
    expiryDate: "12/26",
    isActive: true,
    cardHolder: "Juan Pérez",
  },
  {
    id: "card_002",
    accountId: "acc_001",
    cardNumber: "**** **** **** 5678",
    cardType: "credit",
    expiryDate: "08/25",
    isActive: false,
    cardHolder: "Juan Pérez",
  },
]

export const mockMoneyRequests: MoneyRequest[] = [
  {
    id: "req_001",
    amount: 5000,
    description: "Cena de anoche",
    requesterId: "2",
    requesterName: "Carlos Rodríguez",
    status: "pending",
    createdAt: "2024-01-15T09:00:00Z",
    expiresAt: "2024-01-22T09:00:00Z",
  },
  {
    id: "req_002",
    amount: 12000,
    description: "Combustible viaje",
    requesterId: "4",
    requesterName: "Luis Fernández",
    status: "accepted",
    createdAt: "2024-01-14T15:30:00Z",
    expiresAt: "2024-01-21T15:30:00Z",
  },
]
