import type { Account, Contact, Transaction, Investment, PaymentMethod } from "./types"

export const mockAccount: Account = {
  id: "acc_001",
  userId: "user_001",
  balance: 1250000,
  currency: "ARS",
  accountNumber: "1234567890",
  accountType: "checking",
  isActive: true,
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2024-01-22T10:30:00Z",
}

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Elyer Saitest",
    initials: "ES",
    hasUala: true,
    phone: "+54 9 11 1234-5678",
    email: "elyer@example.com",
    recentTransfers: [
      { amount: 40000, date: "18/01", type: "sent" },
      { amount: 30000, date: "03/01", type: "received" },
      { amount: 50000, date: "19/12/2024", type: "sent" },
    ],
  },
  {
    id: "2",
    name: "Pato Free Range",
    initials: "PF",
    hasUala: true,
    phone: "+54 9 11 2345-6789",
    email: "pato@example.com",
    recentTransfers: [
      { amount: 25000, date: "15/01", type: "received" },
      { amount: 12000, date: "10/01", type: "sent" },
    ],
  },
  {
    id: "3",
    name: "Ana Martínez",
    initials: "AM",
    hasUala: true,
    phone: "+54 9 11 3456-7890",
    email: "ana.martinez@example.com",
    recentTransfers: [
      { amount: 75000, date: "20/01", type: "sent" },
      { amount: 15000, date: "12/01", type: "received" },
    ],
  },
  {
    id: "4",
    name: "Carlos Rodriguez",
    initials: "CR",
    hasUala: true,
    phone: "+54 9 11 4567-8901",
    email: "carlos.rodriguez@example.com",
    recentTransfers: [{ amount: 35000, date: "17/01", type: "received" }],
  },
  {
    id: "5",
    name: "Lucía Fernández",
    initials: "LF",
    hasUala: true,
    phone: "+54 9 11 5678-9012",
    email: "lucia.fernandez@example.com",
    recentTransfers: [],
  },
  {
    id: "6",
    name: "Diego Morales",
    initials: "DM",
    hasUala: true,
    phone: "+54 9 11 6789-0123",
    email: "diego.morales@example.com",
    recentTransfers: [
      { amount: 22000, date: "14/01", type: "sent" },
      { amount: 18000, date: "08/01", type: "received" },
      { amount: 45000, date: "02/01", type: "sent" },
    ],
  },
  // Contacts without Ualá
  {
    id: "7",
    name: "María González",
    initials: "MG",
    hasUala: false,
    phone: "+54 9 11 7890-1234",
    email: "maria.gonzalez@example.com",
    recentTransfers: [{ amount: 60000, date: "16/01", type: "sent" }],
  },
  {
    id: "8",
    name: "Roberto Silva",
    initials: "RS",
    hasUala: false,
    phone: "+54 9 11 8901-2345",
    email: "roberto.silva@example.com",
    recentTransfers: [],
  },
  {
    id: "9",
    name: "Carmen López",
    initials: "CL",
    hasUala: false,
    phone: "+54 9 11 9012-3456",
    email: "carmen.lopez@example.com",
    recentTransfers: [
      { amount: 28000, date: "13/01", type: "received" },
      { amount: 33000, date: "05/01", type: "sent" },
    ],
  },
  {
    id: "10",
    name: "Fernando Ruiz",
    initials: "FR",
    hasUala: false,
    phone: "+54 9 11 0123-4567",
    email: "fernando.ruiz@example.com",
    recentTransfers: [
      { amount: 95000, date: "19/01", type: "sent" },
      { amount: 42000, date: "11/01", type: "received" },
    ],
  },
  {
    id: "11",
    name: "Valentina Castro",
    initials: "VC",
    hasUala: false,
    phone: "+54 9 11 1234-5670",
    email: "valentina.castro@example.com",
    recentTransfers: [],
  },
  {
    id: "12",
    name: "Sebastián Torres",
    initials: "ST",
    hasUala: false,
    phone: "+54 9 11 2345-6701",
    email: "sebastian.torres@example.com",
    recentTransfers: [{ amount: 17000, date: "09/01", type: "received" }],
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    type: "transfer",
    amount: -50000,
    description: "Transferencia a Ana Martínez",
    date: "2024-01-20",
    status: "completed",
    category: "Transferencias",
    contactName: "Ana Martínez",
    balance: 1200000,
  },
  {
    id: "txn_002",
    type: "deposit",
    amount: 100000,
    description: "Depósito en efectivo",
    date: "2024-01-19",
    status: "completed",
    category: "Depósitos",
    balance: 1250000,
  },
  {
    id: "txn_003",
    type: "payment",
    amount: -25000,
    description: "Pago de servicios - Luz",
    date: "2024-01-18",
    status: "completed",
    category: "Servicios",
    balance: 1150000,
  },
  {
    id: "txn_004",
    type: "transfer",
    amount: -30000,
    description: "Transferencia a Carlos Rodriguez",
    date: "2024-01-17",
    status: "completed",
    category: "Transferencias",
    contactName: "Carlos Rodriguez",
    balance: 1175000,
  },
  {
    id: "txn_005",
    type: "withdrawal",
    amount: -15000,
    description: "Retiro en cajero automático",
    date: "2024-01-16",
    status: "completed",
    category: "Retiros",
    balance: 1205000,
  },
]

export const mockInvestments: Investment[] = [
  {
    id: "inv_001",
    name: "Fondo Común de Inversión",
    type: "mutual_fund",
    amount: 500000,
    currentValue: 525000,
    returnPercentage: 5.0,
    risk: "medium",
    description: "Fondo diversificado de renta mixta",
  },
  {
    id: "inv_002",
    name: "Plazo Fijo UVA",
    type: "fixed_term",
    amount: 300000,
    currentValue: 315000,
    returnPercentage: 5.0,
    risk: "low",
    description: "Plazo fijo ajustado por inflación",
  },
]

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: "pm_001",
    type: "debit_card",
    name: "Tarjeta de Débito Ualá",
    lastFour: "1234",
    isDefault: true,
    expiryDate: "12/26",
  },
  {
    id: "pm_002",
    type: "credit_card",
    name: "Tarjeta de Crédito Visa",
    lastFour: "5678",
    isDefault: false,
    expiryDate: "08/25",
  },
]
